export const LOAD_USER = "LOAD_USER";
export const UPDATE_USER = "UPDATE_USER";

export const LOAD_TENANTS = "LOAD_TENANTS";

export const LOAD_PUBLIC_SYSTEMS = "LOAD_PUBLIC_SYSTEMS";
export const LOAD_SYSTEMS = "LOAD_SYSTEMS";
export const LOAD_TENANT_SYSTEMS = "LOAD_TENANT_SYSTEMS";
export const LOAD_TENANT_PHASE_MANUAL_ENTRIES =
  "LOAD_TENANT_PHASE_MANUAL_ENTRIES";
export const ADD_TENANT_PHASE_MANUAL_ENTRY = "ADD_TENANT_PHASE_MANUAL_ENTRY";
export const UPDATE_TENANT_PHASE_MANUAL_ENTRY =
  "UPDATE_TENANT_PHASE_MANUAL_ENTRY";
export const DELETE_TENANT_PHASE_MANUAL_ENTRY =
  "DELETE_TENANT_PHASE_MANUAL_ENTRY";
export const SELECT_SYSTEM = "SELECT_SYSTEM";
export const DESELECT_SYSTEM = "DESELECT_SYSTEM";

export const LOAD_AVAILABLE_JOB_TYPES = "LOAD_AVAILABLE_JOB_TYPES";
export const LOAD_JOB_OPTIONS = "LOAD_JOB_OPTIONS";
export const LOAD_TENANT_JOB_STATUS = "LOAD_TENANT_JOB_STATUS";
export const LOAD_TENANT_JOB_HISTORY = "LOAD_TENANT_JOB_HISTORY";
export const LOAD_TENANT_JOB_HISTORY_IN_RANGE =
  "LOAD_TENANT_JOB_HISTORY_IN_RANGE";
export const LOAD_TENANT_JOB_STATUSES = "LOAD_TENANT_JOB_STATUSES";
export const CREATE_SCHEDULED_JOB = "CREATE_SCHEDULED_JOB";
export const UPDATE_SCHEDULED_JOB = "UPDATE_SCHEDULED_JOB";
export const DELETE_SCHEDULED_JOB = "DELETE_SCHEDULED_JOB";
export const UPDATE_JOB_STATUS = "UPDATE_JOB_STATUS";
export const LOAD_JOB_TYPE_CONFIG_SCHEMA = 'LOAD_JOB_TYPE_CONFIG_SCHEMA';